spring:
  application:
    name: liqui-jpa
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.xml
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER_ADMIN}
    password: ${DB_PASSWORD_ADMIN}
    default-schema: ${DB_SCHEMA}
    liquibase-schema: ${DB_SCHEMA}